export const AXIS_UPLOAD_SESSION_STORE = 'AXIS_UPLOAD_SESSION_STORE';
export const AXIS_UPLOAD_FILE_STORE = 'AXIS_UPLOAD_FILE_STORE';
export const AXIS_UPLOAD_RECEIPT_SIGNER = 'AXIS_UPLOAD_RECEIPT_SIGNER';
